### ISSUE TITLE
Redefine a "primary"

### ISSUE THREAD

**Issue by allen-cain** [uptane/uptane-standard#109]
Current definition of a primary in the spec is: "A primary ECU downloads from a repository and verifies update images and metadata for itself and for secondary ECUs, and distributes images and metadata to secondaries. Thus, it requires extra storage space and a connection to the internet."

I believe the requirement for the primary to have a connection to the Internet does not allow for different in-vehicle network architectures that may leverage multiple "primary-like" ECUs throughout the vehicle, which do **not** have an Internet connection. 

> @JustinCappos question on the Forum: "Where would the primary get updates from in this case?" 

I believe these ECUs may receive updates from another primary (potentially one with internet connection) or directly from an external interface (e.g., USB, OBD-II, etc.).

Just for clarity - I am **not** proposing adding another classification of ECU. I am simply proposing removing all dependencies of external connections when referring to a primary.

**Comment by JustinCappos** [comment]
So part of the reason this is a fairly loaded suggestion is that by having multiple active primaries in a vehicle, there needs to be some mechanism for deciding which primary should update an ECU.  If multiple primaries might try to update the same ECU, this can lead to a host of mix-and-match-eque attacks.  

What are your thoughts on the best way to handle this?  We discuss having backup primaries, etc. already.

**Comment by trishankatdatadog** [comment]
What's our decision on this? Are you making a PR @allen-cain ?

**Comment by jhdalek55** [comment]
See PR#112

**Comment by tkfu** [comment]
Closed by #112
