### ISSUE TITLE
Threat model

### ISSUE THREAD

**Issue by OYTIS** [uptane/uptane-standard#11]
How the community feels about the idea of first describing Uptane threat model and security guarantees before diving into the implementation requirements?
I strongly feel that the standard needs it so that implementers can understand what are the security tradeoffs when adapting the standard to one's needs. On the other hand I'm not confident that I can write this document because by expertise in security is not that high.
Some threat model is already described in the "design overview" google doc, my idea is here

- To have it in the standard as soon as possible.
- To apply it more systematically in the work on the standard, so that every requirement (e.g. having snapshot metadata for director repo) can be traced back to the specific threat/security guarantee.

Thanks,
Anton Gerasimov
Embedded Software Developer at HERE Technologies

**Comment by JustinCappos** [comment]
So, I like the idea.  I do like explaining the rationale and feel this has
value.

As for encouraging people to adapt things for their use case, the
deployment guidelines will cover this.  The rest of the standard consists
of things that should absolutely be done for security.

**Comment by tkfu** [comment]
I've expanded the threat model chapter in commit 7829f81b1238d0bacb01df60cf42381c3cb5e5d6 in #10. I haven't done anything yet on security guarantees, though.

**Comment by JustinCappos** [comment]
These additions look good to me.
