### ISSUE TITLE
[Minor Issue] Inconsistent capitalization of "Image", "Director", and "Target" repositories

### ISSUE THREAD

**Issue by plapczyn** [uptane/uptane-standard#116]
It seems to be about 50/50 that we capitalize "Image" "Director", and "Target" when talking about the repositories. We should make a decision one way or another and make the document consistent.

**Comment by jhdalek55** [comment]
I agree. I actually did a pass sometime back and capitalized these terms
throughout (as they really are proper nouns). But I'm assuming as new
additions were made that the consistency was lost.

I think they should be capitalized, but if it reads like overkill, we can
change them. The key as you state is to be consistent. I can take care of
this once I know the will of the group.

Lois

**Comment by iramcdonald** [comment]
Hi Phil and Lois,

I strongly agree that these always be capitalized.  They're fundamental
entities in any Uptane implementation.  I also strong feel that Primary
and Secondary should always be capitalized.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by jhdalek55** [comment]
If we are agreed that Image, Target and Director should always be capitalized, I can probably do a pass early this week and correct all these. Should I change Primary and Secondary as well, as per Ira's suggestion?

**Comment by iramcdonald** [comment]
Hi,

Rationale:  Primary and Secondary are the client ends (Secondary indirectly
via Primary) of all transactions with the Director and Image Repository (who
are the server ends).  Therefore they should be titlecase (first letter
capped).

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by jhdalek55** [comment]
Fine. I'll take care of this.

Lois

**Comment by jhdalek55** [comment]
PR#125 takes care of this concern.

**Comment by jhdalek55** [comment]
This issue can now be closed via PR#125.
