### ISSUE TITLE
Misc clarifications needed

### ISSUE THREAD

**Issue by mcvand** [uptane/uptane-standard#119]
Section 2.2.
Primary/Secondary ECUs: Terms used to describe the control units within a ground vehicle. **A primary ECU** downloads and **verifies update images and metadata for itself and for secondary ECUs**, and distributes images and metadata to secondaries. Thus, it requires extra storage space and a means to download images and metadata. **Secondary ECUs** receive their update images and metadata from the primary, and only need to v**erify and install their own metadata and images**.
>>> is the metadata for secondaries doubly verified, once by primary and another time by secondary? Or are those two different types of verifications? (e.g. signature vs. just hash). The standard explains that secondaries must verify the metadata for their images; but the definition is misleading.
>>> Terminology needs a **metadata** definition for this context.

Section 3.2.1 Use cases.
>>> There is no use case listed for when an ECU is swapped with another at a dealer aftermarket. Presumably the director should know about this change for that particular VIN. The difference with this use case is that it’s not OEM-initiated.

Section 5.2.6
“A single mapping indicating that all images (*) MUST be signed by both the Director and Image repository”
>> Unclear:  Single mapping of what to what? Isn’t this just an indication? And, if this is a general Uptane requirement, why does it have to be in a config file? The next paragraph explains it better. Thus this third bullet seems out of place.

Section 5.3.2.1 “The Director MAY encrypt images for ECUs that require it.”
>> Is there a secure way for an ECU to come with a requirement that images must be encrypted? E.g. serial number, model/type, and image encryption flag. In the standard there are requirements around image encryption but they seem to have nothing to do with the actual Ecu that may or may not require it. The OEM or Tier-n should decide this. O/w these requirements are of limited value.

**Comment by jhdalek55** [comment]
@trishankkarthik,  @patrickvacek, @plapczyn can one or several of you jump here and review these clarifications?

**Comment by patrickvacek** [comment]
> is the metadata for secondaries doubly verified, once by primary and another time by secondary? Or are those two different types of verifications? (e.g. signature vs. just hash). The standard explains that secondaries must verify the metadata for their images; but the definition is misleading.
> Terminology needs a **metadata** definition for this context.

Yes, doubly verified. In the full verification case, they are essentially the same verification. In the partial verification case, it is different, which may be why there is some ambiguity here. What is your concern? I'm not sure if I've understand what you mean by needing a "metadata definition".

> There is no use case listed for when an ECU is swapped with another at a dealer aftermarket. Presumably the director should know about this change for that particular VIN. The difference with this use case is that it’s not OEM-initiated.

Yes, this is a complicated scenario. IIRC this is mentioned in the deployment considerations. (If it isn't, it probably should be.) In any case, if we were to want to put something about this in the standard, that would probably not be something we could do in time for the 1.0 release. 

> Is there a secure way for an ECU to come with a requirement that images must be encrypted? E.g. serial number, model/type, and image encryption flag. In the standard there are requirements around image encryption but they seem to have nothing to do with the actual Ecu that may or may not require it. The OEM or Tier-n should decide this. O/w these requirements are of limited value.

This seems implementation-dependent to me. It could belong in deployment considerations. It is possible an appropriate sentence or two could be put in the standard, but anything more than that is probably too complex to get into the 1.0 release.

**Comment by iramcdonald** [comment]
Hi,

I agree with Patrick that it's too late too make substantial changes
to Uptane Standard v1.0.  I also think that discussion of many use
cases belongs in the Deployment Considerations.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by trishankkarthik** [comment]
(Sorry, I'm OOO this week... thanks for covering for me!)

**Comment by mcvand** [comment]
Thank you very much for your response Patrick.
Fully agree it would be too late for changes. Answers are satisfactory and will watch for the opportunity to put them into the Deployment considerations when the time comes.

​​​​​
Thanks,
Michaela~

**Comment by mcvand** [comment]
Agreed in 6/25 mtg to add definition of metadata from NIST (https://csrc.nist.gov/glossary/term/metadata) but those are either circular or not directly applicable.  Suggest this, veterans please correct: "Information associated with a role or an image, containing characteristics or parameters thereof: e.g. cryptographic material parameters, file names and versions."

 Also agreed to slightly modify the definition of Primary/Secondary ECU to clarify the verification is done by both (added "also".. .sounds a bit strange though):.  e.g. "Secondary ECUs receive their update images and metadata from the primary, and only**/also** need to verify and install their own metadata and images."

**Comment by iramcdonald** [comment]
Hi Michaela,

Thanks very much for your careful reading of the Uptane Standard draft!

I like your suggested definition of metadata within the context of Uptane.

But, the US NIST Glossary definition at:

  https://csrc.nist.gov/glossary/term/metadata

doesn't look circular or inapplicable to me:

  "Information describing the characteristics of data including, for
example, structural
metadata describing data structures (e.g., data format, syntax, and
semantics) and
descriptive metadata describing data contents (e.g., information security
labels)."

I suggest we list *both* definitions - first the NIST one, which is sound
information
theory, and second the Uptane specialization you proposed.

WDYT?

Cheers,
- Ira


Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by mcvand** [comment]
Hello Ira,

Glad you find the NIST one applicable (the “syntax” and “info security labels” seemed strange to me).
About the circular nature: the NIST definition of metadata contains 2 counts of the word “metadata”.

Thanks,
​​​​​
Michaela Vanderveen
Senior Standards Manager
Mobile +1 (925) 596-8608
Office +1 (925) 242-8563
Email: mivanderveen@blackberry.com<mailto:mivanderveen@blackberry.com>

[http://blackberrysquare/articles/2016/2303/sig_tag_1.png]

**Comment by iramcdonald** [comment]
Hi Michaela,

I was thinking of "syntax" as being very important in POUF profiles of
Uptane
implementations.

While the NIST definition of metadata contains two instances of metadata,
those are in *examples* of classes of metadata - which seemed like useful
examples to me, because we use the word metadata in both of these senses
in various parts of the Uptane Standard.

Cheers,
- Ira

PS - Running away from this computer to play music all evening at a monthly
session at a Moose Lodge 75 miles away.


Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by jhdalek55** [comment]
I can add this definition as I'm making at capitalization changes.

**Comment by iramcdonald** [comment]
Hi Lois,

Thanks.

Capitalization:  Conformance keywords (MUST, SHALL, SHOULD,
and *MAY*) must be all-caps throughout.  In addition, by IETF BCP 14
rules, they must not be used in lowercase anywhere.  In particular,
*MAY* is probably still misused in lowercase.  IEEE-ISTO PWG and
others use "could" or "can" to replace lowerocase "may" where it was
not meant to specify a formal conformance option.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by jhdalek55** [comment]
PR#125 adds the definition of metadata discussed in this issue. I believe we agreed the other issues here would be moved to the pending deployment issues list. @mcvand, if you want to summarize the other concerns touched on here, I will add them to my offline deployment issues list until our deployment materials have a new home.

**Comment by mcvand** [comment]
Yes, we agreed that the other issues raised in #119 can be addressed in the deployment considerations later. Thus yes, the offline issue list you are keeping is a good place for now.
Should I close this issue now myself or can you?

​​​​​
Thanks,
Michaela~

**Comment by jhdalek55** [comment]
I'm not sure I can close it. I guess you can try, as the creator, but maybe wait till after tomorrow's meeting. Since I referenced this issue in my PR I'm not sure how that might be affected if you close this now. It probably has no effect, but don't know enough about github to be sure.

**Comment by jhdalek55** [comment]
This issue can now be closed via PR#125
