### ISSUE TITLE
Clarify "download and verify images" language

### ISSUE THREAD

**Issue by zabbal** [uptane/uptane-standard#121]
In "Download and verify images" subsection spec says:
"There may be several different filenames that all refer to the same image binary, as described in {{targets_meta}}. The primary SHALL associate each image binary with each of its possible filenames."

1) I think this should actually refer to #metadata_filename_rules because that's where bit about different names for the same file is actually clarified.

2) The last sentence is rather confusing (might be just my English though) - the way I understand it, it suggest for ECU to obtain for each "acme_firmware.bin" a list of all the names like "aaaa.acme_firmware.bin", "bbbb.acme_firmware.bin" etc where "aaaa" is hash1 (sha256 for example), "bbbb" is hash2 (sha3) and so on.

According to #targets_images_meta the "One or more hashes of the image file, along with the hashing function used" is part of the list obtained from the targets role.

So if the intention is to make sure ECU checks every hash of a given firmware (and not just a single one) it's better to state this explicitly and refere to #targets_images_meta. If not than it deserves clarification.

There might be more hashes of a given image in the repository than supplied via targets role so requesting "each of its possible filenames" seems too broad.

**Comment by jhdalek55** [comment]
Can we get some feedback on this and if one or two are in agreement we can ask Max to do a pull request.

**Comment by iramcdonald** [comment]
Hi,

I agree with all of Max's comments.  The current text is obscure
and would lead to inconsistent implementations.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434
