### ISSUE TITLE
Deployment considerations URL is broken

### ISSUE THREAD

**Issue by patrickvacek** [uptane/uptane-standard#135]
Try going to https://uptane.github.io/uptane-standard/uptane-standard.html#DEPLOY and follow the link to https://uptane.github.io/deployment/introduction.html. Should we fix that URL to redirect to https://github.com/uptane/deployment-considerations, or should we change the URL in the standard?

While we're at it, most of the time that the deployment doc is mentioned in the standard, it is not cited with "[DEPLOY]". That's easy to fix albeit not very critical.

**Comment by jhdalek55** [comment]
First off, thanks for picking this up, Patrick.
Obviously we have to fix the broken link. The question at this point is which of the two links should it point to at this time--the stable, but perhaps a bit out of date Google doc, or the very much in progress repo. My inclination is towards the latter, but given that the layout of the repo is still very raw, the stable document is probably a better resource for expanding on whatever points the Standard eludes to when this reference is suggested.

Thoughts, please?

Lois

**Comment by iramcdonald** [comment]
Hi,

I disagree Lois.  A standard should only point to stable documents.  So the
"old"
Deployment Considerations should be the corrected link in the standard.

Patrick - thanks for finding this rather important flaw.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by jhdalek55** [comment]
Actually we really do agree, Ira. I said my inclination was to point to the repo but my recommendation was the stable doc. Sorry if my engaging in a bit of rhetorical argument structure obscured my meaning.

Lois
