### ISSUE TITLE
Unique Value in Version Report to Prevent Replay

### ISSUE THREAD

**Issue by mnm678** [uptane/uptane-standard#143]
ECU version reports need an element that is guaranteed to change each update cycle. However, ECUs may have a fairly inaccurate source of time that does not change with every version report. If the time is not guaranteed to change, some other element, such as a counter or nonce, must be included in the version report. The director should check this element to ensure the version report is not replayed.

**Comment by iramcdonald** [comment]
Hi Marina,

Looks fine to me.

Note that a counter is actually preferable to a random nonce, because
it makes ECU Version Manifest sequence correlation straightforward
(for Audit Trail logging).

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by allen-cain** [comment]
Hi @mnm678 - 

Thank you for this comment.

I have a couple of comments/questions:

Current v1.0 spec Section 5.4.2.1.2 indicates a _'cryptographic_ nonce' and _'latest known time'_ is included in the payload.
`     Is your proposal to change _'cryptographic nonce'_ with _'counter'_, -or- to add more detail as to the use of the cryptographic nonce, -or- to add a _'counter'_ as an addition required attribute for the data payload?
`(I believe) one reason the _'cryptographic nonce'_ was included is for the ECU to send the  _'cryptographic nonce'_ to the TimeServer. 
The TimeServer would in turn, provide a signed response with _'cryptographic_nonces'_ received in conjunction with an updated time. 
Thus the vehicle (and associated ECUs) can update their _'latest known time'_. 
[I am 100% open to critiques in my memory of reasoning why this was included]


If the desire is to detect an ECU-version replay attack from Server, can this be achieved with _'last known time'_ and  _'cryptographic nonce'_ or are there use cases where they are insufficient & a monotonically increasing _'counter'_  is needed?


Thanks for your help in answering -

**Comment by mnm678** [comment]
@allen-cain 

In the case that the Time Server is used, your description is accurate. The nonce is used for the time server and can be used to prevent a replay.

The concern (as I understand it) is that in cases where the Time Server is not used a cryptographic nonce is a lot of overhead for ECUs. A counter would also suffice to prevent a replay attack.

So the proposal here is to update the standard to allow for either a cryptographic nonce or a counter to be included in the ECU version report.

**Comment by iramcdonald** [comment]
Hi,

Marina summarized the thinking very well.

Let me amplify by saying that the IETF NTP WG is approaching
finalization of NTS for NTP, which will give high security to NTP
and would be *far* preferable to any Uptane-specific Time Server.

ITU-T, ETSI, ISO, and others will certainly adopt Secure NTP
(including in the automotive software update standards), so the
useful lifetime of the Uptane Time Server is far shorter than the
average lifetime of a new vehicle.

Does that help?

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by jhdalek55** [comment]
Marina, do you want to do a first pass at creating a pull request for this topic that incorporates Ira's comments? The discussion certainly can continue here, but I think it can be better addressed by trying to get the essence of this issue into actual words. 

Thanks

Lois
