### ISSUE TITLE
Snapshot check for Targets metadata filenames

### ISSUE THREAD

**Issue by patrickvacek** [uptane/uptane-standard#149]
Step 6 of https://uptane.github.io/uptane-standard/uptane-standard.html#check_snapshot (How to check Snapshot metadata) reads "Check that each Targets metadata filename listed in the previous Snapshot metadata file is also listed in this Snapshot metadata file. If this condition is not met, discard the new Snapshot metadata file, abort the update cycle, and report the failure. (Checks for a rollback attack.)"

The Targets being referred to here include the top-level Targets and any delegations. What were to happen if one of the delegations listed were removed? My understanding was that it was possible for delegations to be removed, and as such, this check would be invalidated. What should one then do to delete a delegation?

**Comment by patrickvacek** [comment]
Further information: TUF also has the same requirement, but whereas Uptane says nothing about delegation revocation, TUF says (in 2.1.2 Targets role), "Any delegation can be revoked at any time: the delegating role needs only to sign new metadata that no longer contains that delegation." However, as currently written, the Snapshot metadata would still have to list that delegation indefinitely, despite that it has been revoked.

**Comment by JustinCappos** [comment]
The problem here relates to an attacker that tries to do a rollback attack as follows:

1. target foo is version 8 and attacker wants to roll it back to version 1.  Snapshot lists foo version 8

2. A new snapshot is listed with foo removed.  ECUs update and remove the old snapshot metadata, losing information about what the version of foo should be.

3. A new snapshot is listed with foo version 1.  ECUs that received the snapshot from step 2 (with foo removed) will update because they are now unaware that the latest version of foo was 8, since the snapshot from step 1 was lost.

**Comment by zabbal** [comment]
I think this is one of the cases which has to be part of uptane-tests - it's easy enough to overlook during implementation yet it's a realistic attack scenario.

**Comment by jhdalek55** [comment]
@zabbal Can you perhaps present this as an issue to address on the Test repo pages? Thanks.

**Comment by jhdalek55** [comment]
And, if the attack @JustinCappos  mentioned is dealt with in the Test document, is a further change needed in the Standard?

**Comment by jhdalek55** [comment]
This issue has been sitting here for about a month-plus. @patrickvacek how should we move forward? Should we address this in the test document, or do we need a change in the Standard itself?

**Comment by patrickvacek** [comment]
If I recall our last conversation on this topic correctly, the currently best practice is indeed to leave deleted/revoked delegations in the Snapshot metadata. Otherwise, there is no easy way to prevent a rollback attack that abuses the revocation functionality. I'm interesting in finding a resolution to this, but I don't have a solution in mind. @JustinCappos may have thought about this more and may have some ideas, or perhaps others do. For now, we should just leave the topic open, because it's still an issue, but there isn't a great solution (yet).

**Comment by jhdalek55** [comment]
Ok. I'm not looking to shut the issue down. But, there hadn't been any discussion in a while, so I thought a little prodding was necessary.

**Comment by trishankatdatadog** [comment]
Wasn't this issue resolved elsewhere, where we said that if you use `root` to rotate the `timestamp` and `snapshot` keys, you can reset everything back to 1, and you can also delete revoked delegations?

**Comment by patrickvacek** [comment]
> Wasn't this issue resolved elsewhere, where we said that if you use `root` to rotate the `timestamp` and `snapshot` keys, you can reset everything back to 1, and you can also delete revoked delegations?

That sounds reasonable, but it doesn't entirely mitigate the attack that @JustinCappos had described above. You could still (accidentally or intentionally) rollback a delegation to an earlier version with the new Snapshot.

**Comment by trishankatdatadog** [comment]
@patrickvacek That is only possible if: ECUs delete revoked delegations if they are missing from any new `snapshot` (which is not what the TUF specs says to do), or if attackers have enough `root` keys to rotate `timestamp` and `snapshot`, no?

**Comment by patrickvacek** [comment]
> That is only possible if: ECUs delete revoked delegations if they are missing from any new `snapshot` (which is not what the TUF specs says to do), or if attackers have enough `root` keys to rotate `timestamp` and `snapshot`, no?

Yeah. So I think this falls into the category of "not your biggest concern in this scenario" since if the attackers have root keys they can basically do anything with the repo.

Okay, I think I'm satisfied here. So basically, if you rotate the Timestamp and Snapshot keys (and push new Root metadata with the new keys), you can clear out revoked delegations in the Snapshot and the ECU should respect that (only) in that case. This seems like something worth clarifying, since it's not necessarily obvious. Perhaps this belongs in the deployment considerations?

**Comment by trishankatdatadog** [comment]
@patrickvacek Yes, I think a clarification would be a great idea. Would you mind terribly much sending a quick PR, and I will be happy to review and merge? Thanks!
