### ISSUE TITLE
ABNF isn't a good fit to describe metadata syntax

### ISSUE THREAD

**Issue by tkfu** [uptane/uptane-standard#15]
I know that we had agreed on ABNF for a format to describe the metadata syntax, but after trying to actually implement that decision, I no longer think it is a good one.

The basic problem is this: ABNF is good at, and appropriate for, situations when you need to describe a protocol in great detail, including the exact order and format in which things appear. However, we want to make a spec that describes the overall shape of the metadata, and what fields are necessary, **without** mandating any particular format.

I don't see a reasonable way to write an ABNF description of the metadata that would permit both ASN.1 and JSON, for example.

If we stick with ABNF, we will end up just writing out one particular format of the metadata (say, the JSON version) in ABNF, and then saying in the body text something like this: "However, any metadata format that contains all of the required fields (is isometric to) the one described, is also permitted."

If we're going to have to do that, we might as well write the syntax in a format that's a bit easier to read and understand, like ASN.1 or JSON.

(cc @iramcdonald @OYTIS)

**Comment by JustinCappos** [comment]
Let's make this a discussion item for Friday.

@Lois Anne Delong <lad278@nyu.edu>

**Comment by tkfu** [comment]
As agreed in the meeting, I'll prepare a PR with something like bullet point lists describing the necessary data fields. That means closing #14, as well.
