### ISSUE TITLE
Does partial verification require Root metadata?

### ISSUE THREAD

**Issue by patrickvacek** [uptane/uptane-standard#152]
The standard is currently inconsistent about whether partial verification on a Secondary requires Root metadata. For example:

* Section 5.4.1.1 item 1 ([Build-time prerequisite requirements for ECUs](https://uptane.github.io/uptane-standard/uptane-standard.html#build-time-prerequisite-requirements-for-ecus)) reads "Partial verification ECUs MUST have the Root and Targets metadata from the Director repository."
* Section 5.4.2.6 ([Send metadata to Secondaries](https://uptane.github.io/uptane-standard/uptane-standard.html#send_metadata_primary)) reads "The Primary SHALL send its latest downloaded metadata to all of its associated Secondaries. The metadata it sends to each Secondary MUST include all of the metadata required for verification on that Secondary. [...] For partial verification Secondaries, this includes only the Targets metadata file from the Director repository."
* Section 5.4.4.1 ([Partial verification](https://uptane.github.io/uptane-standard/uptane-standard.html#partial_verification)) only lists time and Targets metadata, but not anything about the Root.

**Comment by JustinCappos** [comment]
The root metadata isn't used by partial verification ECUs.  I think this is an error that should be fixed.

**Comment by jhdalek55** [comment]
At our 1/21 phone meeting, the discussion was that there was a broader issue at work here that required further discussion. Can someone on this thread define the bigger picture to be addressed so we have a basis to continue this discussion, both here and in our next meeting? Thanks.

**Comment by patrickvacek** [comment]
I made [an issue in the Deployment Considerations](https://github.com/uptane/deployment-considerations/issues/40) that explains the broader issue that I'm interested in.

However, while reviewing the existing text of the Standard, I realized that I still think there is an inconsistency in the text, which is explained in my [comment here](https://github.com/uptane/uptane-standard/pull/154#discussion_r369574887).

**Comment by tkfu** [comment]
Standards call on 18.02.2020 concluded that we should add some clarification to the standard on this point, as well as give some more examples in deployment considerations.

**Comment by patrickvacek** [comment]
Closed by https://github.com/uptane/deployment-considerations/pull/42 and https://github.com/uptane/uptane-standard/pull/158.
