### ISSUE TITLE
How to prevent infinite root.json fetches?

### ISSUE THREAD

**Issue by patrickvacek** [uptane/uptane-standard#153]
In section 5.4.4.3 ([How to check Root metadata](https://uptane.github.io/uptane-standard/uptane-standard.html#check_root)), we continue to check for new versions of root.json until the server stops providing them. What if a server were to act maliciously and continue to provide new versions infinitely? Should we enforce a limit to the number of possible root versions, or the number accepted in one update cycle?

**Comment by JustinCappos** [comment]
If an attacker can provide signed, valid versions of root metadata you have a bigger problem than someone generating a lot of files to update.  The root keys are kept offline so there is a manual process to make a change addition.  I can't see a way where this could happen in practice assuming they're managing keys and deploying Uptane according to the guidelines.  

I'd mark this wontfix if we had that label.

**Comment by trishankatdatadog** [comment]
In the reference implementation, we set an [upper bound to the number of root key rotations](https://github.com/theupdateframework/tuf/blob/a6314a0ea27faf1300ec6732ae5a03555463dddd/tuf/settings.py#L111-L113).
