### ISSUE TITLE
Goals for Version 2.0.0

### ISSUE THREAD

**Issue by jhdalek55** [uptane/uptane-standard#156]
On our 1/21 call we spent some time discussing versioning issues and whether we were ready to set a timetable for our next major and minor releases. It was decided that, as a group, we should set some goals for what our next major release (V.2.0.0) should include. This thread has been opened to initiate that conversation. We will be discussing these goals in upcoming phone meetings, but you can use this thread to begin registering some thoughts on the matter.

**Comment by zabbal** [comment]
The #120 seems like rather natural fit.

**Comment by jhdalek55** [comment]
This issue is being left open as a place to introduce discussion of any potential "breaking changes--or changes to the Standard that could potentially impact backwards compatibility with existing implementations. It is not an issue that requires immediate deliberations.

**Comment by jhdalek55** [comment]
As we are not likely to be introducing a 2.0.0 version anytime soon, I'm recommending we close down this issue. It has not served its intended purpose of identifying new  issues to address, so I see no reason to keep it open.

**Comment by iramcdonald** [comment]
+1

Stay safe,
- Ira

*Ira McDonald (Musician / Software Architect)Co-Chair - TCG Trusted
Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: blueroofmusic@gmail.com
<blueroofmusic@gmail.com>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by jhdalek55** [comment]
As noted above, closing this because V.2.0.0 is not on our horizon in the short-term,
