### ISSUE TITLE
Usability Concern w.r.t Proposed Uptane Site

### ISSUE THREAD

**Issue by JosiahOne** [uptane/uptane-standard#16]
Justin suggested I leave my feedback on the draft uptane site here:

Overall, looks great! I did notice though that the usability is a bit poor on
mobile devices. The main issue seems to be that a lot of content is
separated into pages. On desktop this is fine, but on mobile it causes
poor workflow. e.g.:

  1. You open the home page, and scroll down to read more. You quickly
come to the end of the project overview.
  2. It isn't clear that any other contents exists.  BAD
  3. Eventually, you scroll back up and notice a long navigation header.
  4. You tap on a particular section, e.g. "Why Uptane is Needed".
  5. No apparent change is made, because the navigation header still
exists and doesn't change appearance at all.  BAD
  6. Eventually you scroll down and realize the content actually did
change. You read it.
  7. You quickly are back at 2.  BAD

Rinse and repeat.

Not sure if this is easy to fix or not, but thought I would mention it
nonetheless.

**Comment by JustinCappos** [comment]
I'll mention that we at NYU don't have the skillset to do this as far as I am aware.  I'm hoping someone in the community can help out...

**Comment by JosiahOne** [comment]
The WIP source is located here: https://github.com/awwad/awwad.github.io

I'm going to try to take a look. Fix might be as simple as picking a different Jekyll theme.

**Comment by JosiahOne** [comment]
I'm way behind on this, but I do still plan on investigating this before 2019.

**Comment by JosiahOne** [comment]
Unfortunately, I won't be able to look at this anytime soon. In addition to work, I'm now a graduate student, and can't seem to make time for this.

**Comment by jhdalek55** [comment]
Understood. We will look for another way to resolve this. Thanks for
letting us know.

Lois

**Comment by tkfu** [comment]
Closing as wontfix for now; this is also an issue that should be on the [uptane.github.io repo](https://github.com/uptane/uptane.github.io).
