### ISSUE TITLE
Update hash function examples

### ISSUE THREAD

**Issue by zabbal** [uptane/uptane-standard#163]
That's a minor nitpicking but still. We use couple of hash function examples like sha512-224 and SHA512-256. In the https://csrc.nist.gov/publications/detail/fips/180/4/final those are referred to as SHA-512/224 and SHA-512/256 respectively. Let's drop this eyesore and avoid confusion with sha256 by using SHA-224 and SHA-3 instead. I know that SHA-512/224 is not the same as SHA-224 but in this context (just an example of a crypto hash function) it shouldn't matter.

Shall I make a PR?

**Comment by iramcdonald** [comment]
Hi Max

I disagree with this change.  Lack of precision is dangerous.  And SHA-3
is a whole family of hash algorithms w/ different output sizes and default
parameters.  SHA-224 is certainly not a legitimate tag (in either NIST
SP800 specs or the IETF's IANA algorithm registries).

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
(permanent) PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by trishankatdatadog** [comment]
I agree. In fact, if we are to be even more precise, we should say things like `SHA2-256` and `SHA3-256` to distinguish between the two.

**Comment by iramcdonald** [comment]
Hi,

I agree with Trishank.  The IANA TLS Parameters registry always
distinguishes
between SHA2 and SHA3 families of hash algorithms.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
(permanent) PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by jhdalek55** [comment]
@zabbal  given the comments from @iramcdonald and @trishankatdatadog, what action, if any, is required here?

**Comment by zabbal** [comment]
Created PR which incorporates feedback from the comments: https://github.com/uptane/uptane-standard/pull/166

**Comment by patrickvacek** [comment]
Fixed by https://github.com/uptane/uptane-standard/pull/166.
