### ISSUE TITLE
Deployment Considerations - CONDITIONALLY REQUIRED

### ISSUE THREAD

**Issue by allen-cain** [uptane/uptane-standard#170]
My understanding is that the Deployment Considerations document is intended to provide an implementer/adopter guidance on things they should consider when deploying an Uptane solution.
Considering this, should Deployment Considerations have "CONDITIONALLY REQUIRED" requirements?

**Comment by jhdalek55** [comment]
@Iramcdonald. Your insight on this issue is requested. Thanks.

**Comment by iramcdonald** [comment]
Hi,

Yes, it would be reasonable for the Deployment Considerations to make
frequent use of CONDITIONALLY REQUIRED, as Allen suggested.

Cheers,
- Ira


*Ira McDonald (Musician / Software Architect)Co-Chair - TCG Trusted
Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: blueroofmusic@gmail.com
<blueroofmusic@gmail.com>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by jhdalek55** [comment]
The issue posted here is simply whether we should allow this option. What, if anything, would actually need to be changed in the Deployment pages? If we are agreed that conditionally required is permissible, do we need a PR to make this decision official?

**Comment by tkfu** [comment]
As discussed in the call on 1/9/2020, CONDITIONALLY REQUIRED and SHALL are both acceptable in best practice/deployment documentation. We can use them where appropriate.
