### ISSUE TITLE
Standard Inconsistency

### ISSUE THREAD

**Issue by allen-cain** [uptane/uptane-standard#175]
Section 5.4.2.5 allows for a Secondary to <ins>not</ins> receive the latest attested time due to `not [having] the capacity to verify a time message`.
Yet, Section 5.4.3 & Section 5.4.3.1 requires all ECUs to verify the latest attested time.

<ins>**Proposal:**</ins> Update Sections 5.4.3 & 5.4.3.1 to optional for ECUs which do not have the capacity to verify a time message.

**Comment by iramcdonald** [comment]
Hi,

I agree - this is an outright bug in the current Standard!

We should not defer this consistency fix to v2.0.0.

Cheers,
- Ira


*Ira McDonald (Musician / Software Architect)Co-Chair - TCG Trusted
Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: blueroofmusic@gmail.com
<blueroofmusic@gmail.com>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by jhdalek55** [comment]
Can someone suggest the appropriate wording for a PR here? It seems like it should be a simple issue to address, though we probably will need to review the document to make sure this inconsistency doesn't exist elsewhere.

**Comment by jhdalek55** [comment]
Adding wording on 9/13 that should address this issue.

**Comment by jhdalek55** [comment]
Closed this issue via PR#180

**Comment by patrickvacek** [comment]
Fixed by https://github.com/uptane/uptane-standard/pull/180.
