### ISSUE TITLE
Image verification procedure doesn't specify that the length should be checked

### ISSUE THREAD

**Issue by tkfu** [uptane/uptane-standard#178]
In #177, @cwaldren pointed out that the standard doesn't require the client to verify that the image it has downloaded is the right size. I believe this is just an oversight we should fix. The only question, I think, is whether it's a MUST or a SHOULD.

**Comment by iramcdonald** [comment]
Hi Jon,

I agree that it's an oversight (not checking the size of an image).

And I'm being a broken record.  BUT, if we want a new MUST in the
Standard, then it's a breaking change and requires a 2.0 release.  So
I suggest it be fixed (for 1.1 release) w/ a SHOULD and a rationale.

Cheers,
- Ira


*Ira McDonald (Musician / Software Architect)Co-Chair - TCG Trusted
Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: blueroofmusic@gmail.com
<blueroofmusic@gmail.com>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by jhdalek55** [comment]
Make this a should and submit as a pull request as per discussion in 9-1-20. But tag as 2.0.0 the issue of making image size a MUST.

**Comment by jhdalek55** [comment]
@tkfu should we open a new issues for 2.0.0.  for the bigger issue of changing the need to verify image to a MUST?

**Comment by tkfu** [comment]
Yes, definitely.

**Comment by jhdalek55** [comment]
Issue #181 was opened to remind us of the need for a breaking change in version2.0.0.
