### ISSUE TITLE
Standard vs Standards

### ISSUE THREAD

**Issue by patrickvacek** [uptane/uptane-standard#185]
There are six places where we say "the Uptane Standard" or "this Standard". There are three places where we say "Standards", as in, "Uptane Standards" or "these Standards". The plural sounds weird to me. What's the going recommendation here?

**Comment by patrickvacek** [comment]
Thanks! Fixed by https://github.com/uptane/uptane-standard/pull/184, to which I added another commit.

**Comment by jhdalek55** [comment]
I agree. If we are referring to the "Uptane Standard" or the "Standard" (but still referring to the Standard document, I agree it should be capitalized.
