### ISSUE TITLE
Delegations: "target name must match"

### ISSUE THREAD

**Issue by patrickvacek** [uptane/uptane-standard#187]
In the [delegation resolution section](https://uptane.github.io/uptane-standard/uptane-standard.html#rfc.section.5.4.4.7), we write, "For the delegation to apply, it MUST include the hardware identifier of the target, and the target name must match one of the delegation’s image paths."

Should the second "must" be capitalized, and can we do that without a major version change? It seems like this was just an oversight, not a change in actual requirements.

**Comment by iramcdonald** [comment]
Hi Patrick,

It's a typo that the second "must" is lowercase.  It should just be changed
to "MUST"
as that was clearly the intent all along.

Cheers,
- Ira

*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: blueroofmusic@gmail.com
<blueroofmusic@gmail.com>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by patrickvacek** [comment]
Thanks. I added another commit to https://github.com/uptane/uptane-standard/pull/184 that fixes this.
