### ISSUE TITLE
References to rejected TAP 5

### ISSUE THREAD

**Issue by mnm678** [uptane/uptane-standard#189]
[TAP 5 has been rejected in TUF](https://github.com/theupdateframework/taps/blob/master/tap5.md), but the standard still refers to this document. The TAP was not rejected for a security-related reason, so this isn't an immediate concern, but it might be better for us to move the relevant content directly into Uptane or remove the references in the standard.

A first step could be to get some feedback about if/to what extent TAP 5 is used in practice in Uptane implementations to get a sense for the best path forward.

**Comment by trishankatdatadog** [comment]
I never liked TAP 5, TBH, it was always too complicated for its own good.

**Comment by jhdalek55** [comment]
I saw that, and was going to raise it as a question when I was done reviewing the document. Thanks for making this an issue so we can address it.

**Comment by jhdalek55** [comment]
During the Uptane Standards meeting on 11/24/20, we decided to hold off on approving the release of V.1.1.0, in part because we felt we needed a bit more time with this issue. We can address it in several ways--change the SHALL to a SHOULD to make it conditional, delete the reference, or point towards its substitute, TAP 13 https://github.com/theupdateframework/taps/pull/118. If possible, try to review that TAP and then add your thoughts to this discussion.

**Comment by patrickvacek** [comment]
@JustinCappos suggested that we might be able to simply replace the TAP 5 references with TAP 13. From a quick review, this seems viable. However, someone more knowledgeable in these use cases should make the call.

**Comment by trishankatdatadog** [comment]
> @JustinCappos suggested that we might be able to simply replace the TAP 5 references with TAP 13. From a quick review, this seems viable. However, someone more knowledgeable in these use cases should make the call.

Exactly. I'm in strong favor for removing TAP 5, and do not think we should even replace with TAP 13 unless there are strong use cases.

**Comment by JustinCappos** [comment]
I'm presuming the TAP 5 references are needed and not superfluous, so we
would need to replace them with something...

**Comment by jhdalek55** [comment]
Maybe this is a stupid suggestion, because I understand why being able to cite a strategy makes it more credible, but could we take out the relevant information from TAP 5 without referencing it as such? Would that be a form of plagiarism?  Because it seems to me that it is the recommended strategy we need and not the reference.

**Comment by trishankatdatadog** [comment]
> I'm presuming the TAP 5 references are needed and not superfluous, so we would need to replace them with something...

You mean the use cases are not superfluous?

**Comment by iramcdonald** [comment]
Hi,

I'm in favor of removing TAP-5 and NOT adding TAP-13 (or any other words)
in this first Uptane errata release.

Cheers,
- Ira

*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: blueroofmusic@gmail.com
<blueroofmusic@gmail.com>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by mnm678** [comment]
Because TAP 13 is slightly different, we would have to slightly re-word the standard rather than just replacing the references to TAP 5 (for example, in [Root Metadata](https://github.com/uptane/uptane-standard/blob/master/uptane-standard.md#root-metadata-root_meta) TAP 13 only allows a mapping of top-level targets). This may even be a breaking change if implementers are currently using TAP 5.

In the interest of getting this release out on time, I would suggest we either use @iramcdonald's suggestion to just remove the references for now, or leave them until the 2.0.0 release when we can replace with TAP 13.

**Comment by patrickvacek** [comment]
So to be clear, there are three places where TAP 5 is mentioned:
1. [5.2.2. Root metadata](https://uptane.github.io/uptane-standard/uptane-standard.html#root_meta): "If this mapping of URLs is used, the implementer SHOULD implement this functionality following [TAP-5] to avoid adding unforeseen security risks." This could be easily replaced with TAP 13 or it could just be removed for now.
2. [5.2.4. Snapshot metadata](https://uptane.github.io/uptane-standard/uptane-standard.html#snapshot_meta): "The Snapshot metadata MAY also list the Root metadata filename and version number. This is not required, particularly for implementations of [TAP-5], but MAY be included in all cases for backward compatibility." The TAP 5 should probably just be removed here. Honestly, this could just be reworded to say that it was suggested to be listed in the past, but provides approximately no security benefit and is not required.
3. [5.4.4.2. Full verification](https://uptane.github.io/uptane-standard/uptane-standard.html#full_verification): "If [TAP-5] is supported and a Primary has an external connection to the Uptane repositories, a Primary ECU SHALL download metadata and images following the rules specified in that TAP." Again, could easily be replaced with TAP 13 or just removed.

I think this is less complicated than we think. However, my concern is that TAP 13 has not been formally accepted yet. Does that matter?

**Comment by iramcdonald** [comment]
Hi Patrick,

Thanks for your careful and concrete analysis.  I agree with your
conclusions.

But, if TAP-13 hasn't been officially approved yet, then we definitely
should NOT
reference it in Uptane v1.1.0.

Cheers,
- Ira

*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: blueroofmusic@gmail.com
<blueroofmusic@gmail.com>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by jhdalek55** [comment]
Can we get a resolution here? We need to do so soon if we are going to approve a final draft.

**Comment by patrickvacek** [comment]
> Can we get a resolution here? We need to do so soon if we are going to approve a final draft.

Here's a shot: https://github.com/uptane/uptane-standard/pull/196. I'm open to other options, but I wanted to get something going.
