### ISSUE TITLE
Add references to TAP 13 (once it is accepted)

### ISSUE THREAD

**Issue by pattivacek** [uptane/uptane-standard#198]
We are [removing references to TAP 5](https://github.com/uptane/uptane-standard/issues/189), which has been more or less replaced by TAP 13, but TAP 13 isn't approved yet. Once it is, we should restore and rework some of [that text](https://github.com/uptane/uptane-standard/pull/196).

**Comment by jhdalek55** [comment]
@trishankatdatadog @mnm678 @JustinCappos what is the current status of TAP 13? Do you think it will be accepted before our June deadline for V.1.2.0? If not, we should change the milestone on this issue.

**Comment by JustinCappos** [comment]
I think it's plausible.  Let's see.  The Notary V2 effort (and possibly
Python community too) will help debug this for us.

**Comment by plapczyn** [comment]
Per 2021-04-27 Uptane meeting, we think it should be plausible to release TAP 13 before the 1.2.0 Uptane release. @mnm678  to add to net TUF meeting agenda.

**Comment by jhdalek55** [comment]
@JustinCappos @mnm678  should we still anticipate this as a 1.2.0 issue?

**Comment by jhdalek55** [comment]
During the 5/25 Uptane Standards meeting it was decided we would re-label this for V.2.0.0. Though there has been some progress on TAP 13, it likely will require a little more time before approval.

**Comment by jhdalek55** [comment]
Thanks, Marina.

**Comment by jhdalek55** [comment]
TAP 13 has been approved as a draft as of 11-3-21. Is this sufficient acceptance to reference it in Uptane? Or, should we wait until it has been approved and merged?

**Comment by mnm678** [comment]
We should wait until it's approved. Some of the implementation details might change, so Uptane implementers should probably wait to implement until acceptance.

**Comment by jhdalek55** [comment]
Since this issue cannot be resolved at this time, can we make a new label, perhaps PENDING, for issues like this for which cannot say when they answered? I would prefer we did not leave issues like this (#162 #198) labeled "2.0.0" on the repo as it gives the appearance that we did not completed these on-time. Failing that can we leave it posted without a version label at all?

**Comment by jhdalek55** [comment]
This is still waiting for TUF approval of TAP 13.

**Comment by jhdalek55** [comment]
I'm pasting in the original references to TAP 5 that were removed. In all these cases, the reference to TAP was taken out, but nothing was substituted. Given that TAP 13 has probably changed a bit over the past three years, would it still be a relevant reference? If not, do we need to bother with this at all, or could we just close this issue?

[5.2.2. Root metadata](https://uptane.github.io/uptane-standard/uptane-standard.html#root_meta): "If this mapping of URLs is used, the implementer SHOULD implement this functionality following [TAP-5] to avoid adding unforeseen security risks." 

[5.2.4. Snapshot metadata](https://uptane.github.io/uptane-standard/uptane-standard.html#snapshot_meta): "The Snapshot metadata MAY also list the Root metadata filename and version number. This is not required, particularly for implementations of [TAP-5], but MAY be included in all cases for backward compatibility." 

[5.4.4.2. Full verification](https://uptane.github.io/uptane-standard/uptane-standard.html#full_verification): "If [TAP-5] is supported and a Primary has an external connection to the Uptane repositories, a Primary ECU SHALL download metadata and images following the rules specified in that TAP."

**Comment by JustinCappos** [comment]
@mnm678 Is the right person to look at this, I think.

**Comment by mnm678** [comment]
TAP 13 only allows mapping for targets files, so isn't relevant in the 5.2.4 case at all.

In general, I think we could just close this until someone requests this feature specifically for Uptane. TAP 13 will work with Uptane, but I think we can leave it out of the standard until there's a need for it.

**Comment by jhdalek55** [comment]
It mnkes sense to me as well to close it, at least for now. Let's leave leave the PR open maybe for a week or so for any dissenting opinions, and then this we'll close it.

**Comment by jhdalek55** [comment]
@mnm678 can you close this, per the decision at the 11/22 Standards meeting? There have been no objections over the past 10 days so I think we're good to go.

**Comment by jhdalek55** [comment]
Thanks, @mnm678 .
