### ISSUE TITLE
Complete Move of Glossary to Deployment Best Practices

### ISSUE THREAD

**Issue by jhdalek55** [uptane/uptane-standard#204]
At @iramcdonald suggestion, I've moved the Glossary/Terminology section to the Deployment pages. Now, I need someone to remove the Terminology piece from the Standard and insert a pointer under the Terminology heading directing readers to the right place in the Deployment document. Thank you.

**Comment by jhdalek55** [comment]
@mnm678 can you perhaps take care of this for me?

**Comment by mnm678** [comment]
Yes, I opened pr #205 to add the pointer.

It looks like the glossary doesn't show up in the deployment best practices toolbar on the website, so I'll open a pr there as well to fix that.

**Comment by mnm678** [comment]
See also uptane/uptane.github.io#37.

**Comment by jhdalek55** [comment]
Fixed via PR #205  and  uptane/uptane.github.io#37
