### ISSUE TITLE
Acting on attacks detected by a vehicle when communication with the cloud has been compromised

### ISSUE THREAD

**Issue by jhdalek55** [uptane/uptane-standard#207]
Related to Issue #206, here is another issue related to possible cloud compromise submitted from the community.

If a vehicle owner gives consent for updates through a smart device, there may not be any method for direct communication between the vehicle and the mobile device, making end-to-end signing difficult. In such a scenario, we  also cannot assume there is any human-machine interface on the vehicle, i.e. no screen, no lights, no buttons. This means even if the vehicle detects an attack, if the only way to inform the user is via the cloud and If the  cloud is compromised, then even that means is lost. 

Do connected vehicles require a minimum user interface - e.g. a "service" light controllable by the primary ECU - to get the full benefit of Uptane?

**Comment by tkfu** [comment]
I'm afraid the answer here is pretty tautological: if a vehicle is designed such that its only way to communicate a fault to the end user is via some cloud service, then yes, a total compromise of that cloud service would indeed mean that the vehicle has lost the ability to communicate the fault. There's no way around that.

However, even if the cloud service is completely compromised and all online keys are under the attacker's control (i.e. everything except the image repo's root and targets metadata signing keys and the director repo's root metadata signing key), Uptane can still provide a number of important guarantees--most notably, although the attacker can install any currently valid software on the repo, they won't be able to upload arbitrary malicious software, and the OEM will be able to do disaster recovery effectively, rotating all compromised keys once they regain control of their cloud infrastructure. Neither of those properties depend on the user interface of the vehicle.

**Comment by tkfu** [comment]
Closing this out due to lack of further activity.
