### ISSUE TITLE
Clarify threshold requirement

### ISSUE THREAD

**Issue by mnm678** [uptane/uptane-standard#209]
In a number of TUF implementations, duplicate signatures with the same keyid have been counted multiple times toward the same threshold (including [the reference implementation](https://github.com/theupdateframework/tuf/security/advisories/GHSA-pwqf-9h7j-7mv8)). The Uptane Standard does not explicitly state that only unique keys be counted toward the threshold, so I could see the same confusion happening here. My proposal is to either:
* Add the word 'unique' to all threshold requirements
* Add a definition clarifying more explicitly that each key may only count toward a threshold once.

**Comment by iramcdonald** [comment]
Hi Marina,

I much prefer your first option - it's unambiguous and easier to implement
and
verify in an audit.

Cheers,
- Ira

**Comment by jhdalek55** [comment]
@mnm678 could you draft a PR for the change you are suggesting?

**Comment by jhdalek55** [comment]
Close with PR #210
