### ISSUE TITLE
Add recommendation that Uptane use some type of transport security

### ISSUE THREAD

**Issue by jhdalek55** [uptane/uptane-standard#221]
At the 10/26 Uptane Standards meeting, it was decided we should add a sentence to the Standard that recommends Uptane use some type of transport security.

**Comment by iramcdonald** [comment]
Hi,

And the rationale for transport security (with *mutual strong
authentication*) is two reasons:
1) Defense in depth (i.e., augments the application layer image
signature/package signature)
2) Complete defense against MiTM attacks during update package download.

Cheers,
- Ira

*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: ***@***.***
***@***.***>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by jhdalek55** [comment]
@iramcdonald, Thanks for adding the motivation. This is helpful.

**Comment by jhdalek55** [comment]
As I was reviewing some old emails, I ran across a recommendation from @iramcdonald that we should add a definition of the concept of "defense in depth" and use this as the rationale for adding some type of transport security. I can probably take care of this and add a bit more to the short discussion of transport security in the Deployment  document. I will use the definition @iramcdonald shared from US NIST IR8183

"Defense-in-depth - The application of multiple countermeasures in a layered
or stepwise manner to achieve security objectives. The methodology involves
layering heterogeneous security technologies in the common attack vectors to
ensure that attacks missed by one technology are caught by another."

**Comment by jhdalek55** [comment]
See PR #120 in Deployment Best Practices.

**Comment by jhdalek55** [comment]
We can close this if we get an approval of Deployment PR #120

**Comment by jhdalek55** [comment]
Closing this issue via approval of Deployment PR#120
