### ISSUE TITLE
Add a SECURITY.md security policy to uptane?

### ISSUE THREAD

**Issue by hexsecs** [uptane/uptane-standard#227]
Github now allows projects to define a security policy to clarify how to contact and report vulnerabilities. 
![image](https://user-images.githubusercontent.com/89217603/143059284-450616c5-3ceb-4073-9030-c9dd52994990.png)

https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

Is this something we feel should be add to our uptane repositories?

**Comment by jhdalek55** [comment]
This sounds like a good idea to me. What do others think?
