### ISSUE TITLE
5.3.2.1 Requirement to peform time check

### ISSUE THREAD

**Issue by RobAirbotics** [uptane/uptane-standard#247]
**5.3.2.1** does not mention the requirement to check the time sent in each ECU version report. In **5.4.2.1.2** it states that the latest verified time shall be sent as part of the manifest, does this not need to be checked?

**Comment by jhdalek55** [comment]
At the 2/14 Uptane Standard meeting, it was decided that the time SHOULD be checked in 5.3.2.1.

**Comment by jhdalek55** [comment]
With the merging of PR #248 we should be able to close this issue.

**Comment by B1TSH3LL** [comment]
i would like to work on this issue.

**Comment by jhdalek55** [comment]
Thanks @mnm678
