### ISSUE TITLE
Support separate keys for signatures and encryption

### ISSUE THREAD

**Issue by OYTIS** [uptane/uptane-standard#3]
Today Uptane specifies one ECU key that is used to sign ECU manifest and also to send encrypted firmware to ECU. It might work fine for RSA, but e.g. with ED/EC crypthography we normally have ED keys for signatures and a separate pair of EC keys for encryption. It shoud be supported in uptane.

**Comment by iramcdonald** [comment]
Hi,

Best practice in all current cryptography is to separate key usage.
Signing keys should never
be used for encryption keys (and vice versa).  This is important to get
right (including for RSA).

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
Jan-April: 579 Park Place  Saline, MI  48176  734-944-0094
May-Dec: PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by JustinCappos** [comment]
Agreed.  We'll clarify this case.

**Comment by OYTIS** [comment]
@iramcdonald Yes, I totally agree, that's why I created this issue. As far as I understand current Uptane specification (the one in Google docs), it defines just one entity called "ECU Key" for both signatures and encryption. I think it should be changed.

**Comment by mnm678** [comment]
I made a proposed change in section A.2 of the Deployment Considerations just above [this bookmark](https://docs.google.com/document/d/17wOs-T7mugwte5_Dt-KLGMsp-3_yAARejpFmrAMefSE/edit#heading=h.u7thrpsnvihd). Let me know if you think this addresses the issue.

**Comment by JustinCappos** [comment]
I feel this has addressed it.  If anyone objects, please reopen and we can discuss.
