### ISSUE TITLE
Full Verification Algorithm Errors (5.4.4.2:11.2)

### ISSUE THREAD

**Issue by awwad** [uptane/uptane-standard#35]
The full verification algorithm for finding image metadata in 5.4.4.2:11.2 is wrong.  (There's an additional, more complex problem that I'll put into a separate issue.)

1. It misses the path/wildcard matching for all delegations.
1. It misses the terminating delegation check for multi-role delegations, and also does not include the minimum-roles-in-agreement threshold for multi-role delegations.
1. It should specifically say you should abort if you are unable to find or verify a particular role; you must not continue to the next delegation.
1. The "skip to 11.3" instructions are potentially misleading.

I'll add the PRs for each of these, but here's the content in case I miss something.

### Item 1: Add missing path/wildcard matching
Add 11.2.0 (really a new 11.2.1 and bump all the numbers up), reading:
- If the delegation does not address the image name being sought -- if none
of the delegation's wildcard paths match this image name -- skip this delegation.

### Item 2: Multi-role delegations have thresholds and can be terminating
Any delegation (including multi-role delegations) can be terminating.  The existing algorithm in the standard doesn't check to see if multi-role delegations are terminating.  It could also be a little clearer and more modular.  Further, it doesn't include the minimum-roles-in-agreement mechanism from TAP 3.

**11.2** should read (addition in bold):
- Recursively search the list of delegations, in order of appearance.  **For each delegation**:

**11.2.1** should read:
- If it is a multi-role delegation [TAP-3], then:
  - First, recurse (11.2) for each role listed as if each is a single-role delegation.
  - Inspect the return values from each:
    - If a minimum number of roles in agreement for this multi-role delegation return the same non-custom metadata (i.e. length and hashes) for the image, then return that metadata for the image.  If the values returned are such that there are multiple sets of non-custom metadata meeting threshold (e.g. if the threshold is 2/4 and two sets of two roles agree on different metadata), then break the tie in favor of the earliest role in the multi-role delegation.    
    - If the minimum number of roles in agreement threshold is not met:
      - If the multi-role delegation was terminating, raise an error indicating that image info could not be verified.
      - If the multi-role delegation was not terminating, return no image info and allow the process to proceed to the next delegation.

### Item 3: Abort if a role is not found
It must be made very clear that if at any point in a traversal, a metadata role cannot be found or verified, the traversal must be aborted entirely and the target not found, whether or not the delegation traversed is terminating.  To not require this is to allow a targeted DoS attack to choose among possible options in a prioritized list of delegations (or competing groups of roles in a multi-role delegation).

**11** should read something like this (addition in bold):
- For each image listed in the Targets metadata file from the Director repository, locate a Targets metadata file that contains an image with exactly the same file name. For each delegated Targets metadata file that is found to contain metadata for the image currently being processed, perform all of the checks in step 10. Use the following process to locate image metadata.  **NOTE that if at any point below, a role you attempt to check for image info cannot be found and verified, you should abort the search and indicate that image metadata cannot be found because of a missing or invalid role file.**

### Item 4: Clarify or remove "skip" instruction
This is a recursive algorithm, so IMO instead of writing "skip to step 11.3", either exclude this instruction entirely ("return" is already in there.) or write "continue to step 11.3".  "Skip to [a step outside the recursion]" implies that the recursion is aborted entirely, but what is happening instead is that we're just returning one step up the recursion chain.  This matters in particular because there are important tail portions of the recursion for multi-role and terminating checks.

**Comment by awwad** [comment]
The three added PRs referenced here (#37, #38, #39) address these four issues.  Please take a peek and yell if there are issues. :)

**Comment by patrickvacek** [comment]
Since all the PRs have been merged, can we close this issue?

**Comment by jhdalek55** [comment]
I would say yes. Sebastien, any reason to keep it open?

Lois

**Comment by awwad** [comment]
Oh, definitely, thank you.
