### ISSUE TITLE
A way to specify packages

### ISSUE THREAD

**Issue by OYTIS** [uptane/uptane-standard#4]
Real-world cases not always match the simple "one ECU <-> one firmware image" scenario. At the very least we can also have:

- Multiple "slots" each with its own image.
- Package-based systems like debian, rpm, apk etc. where we can't realistically even enumerate slots.
- Dynamic data (might be out of scope for Uptane though).

We want to keep it in mind while defining Uptane metadata.

**Comment by JustinCappos** [comment]
The first and third cases you mention, I think Uptane handles.  With
multiple slots, so long as they are not interdependent, this is just the
normal Uptane case with a destination slot for

The second case, we have a rudimentary understanding of the solution here,
but need to really check to understand how best to integrate Uptane with
them.  We're working on this now.

Note, that the systems you mentioned use a moderately secure update
mechanism, albeit not one that is compromise resilient.

**Comment by mnm678** [comment]
It would be possible to implement a package-based system using existing Uptane mechanisms as a secure transport mechanism for other popular package managers. This would involve the director packaging files into any packaging system (e.g., debian or rpm) and using ECU ids to enumerate where various files will go. The package would be transmitted to the primary ECU, which would then unpackage it and send files to the appropriate ECUs.

However, getting the packaging and unpackaging to work would require a lot of additional complexity on the primary ECU codebase. Sending files to specific ECUs would probably be better handled by other Uptane systems for sending dynamic data (e.g., by using the custom field of targets metadata and signing images for a specific ECU). Also, these package management solutions are mostly  useful for dependency resolution and file-granular resource tracking. These two issue don't seem to apply much for the ECU landscape.

Is the motivation of something like this to use a repository manager (e.g., https://www.aptly.info/, artifactory or so?)

**Comment by iramcdonald** [comment]
Hi,

Requirements for dependency resolution and file-granular resource
tracking (e.g., multiple deltas plus calibration updates for each of
several target ECUs in a single package) are common requirements
for at least one OEM I'm very familiar with.  ADAS is rapidly changing
the typical complexity of OTA updates for ECUs.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
Jan-April: 579 Park Place  Saline, MI  48176  734-944-0094
May-Dec: PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by mnm678** [comment]
Explanations of how to do [dependency resolution](https://docs.google.com/document/d/17wOs-T7mugwte5_Dt-KLGMsp-3_yAARejpFmrAMefSE/edit#bookmark=id.g1jn0kq1drz), [delta updates](https://docs.google.com/document/d/17wOs-T7mugwte5_Dt-KLGMsp-3_yAARejpFmrAMefSE/edit#bookmark=id.qm9eyfdabyt9), and [dynamic data](https://docs.google.com/document/d/17wOs-T7mugwte5_Dt-KLGMsp-3_yAARejpFmrAMefSE/edit#bookmark=id.xxwa8jycu29l) are included in the deployment considerations document. 

@iramcdonald Are there any other features needed to do resource tracking? I can add a section that explains how the above elements combine to allow dynamically installing delta based updates.

**Comment by iramcdonald** [comment]
Hi,

Thanks for these updates.

Yes a section about combining these three elements allow dynamically
installing delta-based updates would be good.

Otherwise, I think we're now in much better shape.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
Jan-April: 579 Park Place  Saline, MI  48176  734-944-0094
May-Dec: PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by mnm678** [comment]
I added a section the [deployment considerations](https://docs.google.com/document/d/17wOs-T7mugwte5_Dt-KLGMsp-3_yAARejpFmrAMefSE/edit#bookmark=kix.8d6ux04zwo0) that addresses this use case. I'm closing this issue, but can reopen if there's any further discussion.
