### ISSUE TITLE
Minor Issues and Clarification Requests

### ISSUE THREAD

**Issue by sam-m-weber** [uptane/uptane-standard#43]
Here is a list of more minor issues or requests for clarification, in no particular order.

1. According to the section "Downloading and distributing updates on a primary ECU" the primary will never be updated.  This is probably not what is intended. :-)

2. If full or partial verification fails, then the specification states that an error code should be returned.  To what, and how?  The only place I see reference to this elsewhere is in the ECU version report -- will an update failure only be noticed when the next version report is generated?  And will the primary update itself (assuming issue 1 is fixed) even if one of the secondaries has failed?

3. In previous discussions, it was stated that because flash memory fails if it is written too many times, the number of writes should be minimized.  My recollection is that writing every time an update is checked for was considered too frequent.  Is this still a consideration and, if so, what is the acceptable frequency of updates?

4. The definition and descriptions of "roles" seem inconsistent and unclear to me.  In the "Uptane Role Terminology" and "Roles on repositories" sections the roles are described as active entities; "Distributes and revokes..." etc, but aren't actually defined.  The impression gained is that a role is simply a public/private key pair that is used for one of four or five possible purposes in Uptane.  Could the wording be made clearer?

5. How many role instances are there, and what kinds are there?  From the "Detailed Design of Uptane" it can be inferred that there are at least eight, from the statement that "each" repository has the Root, Timestamp, Snapshot and Target roles. Ie, there is the image repository's Root role, the Director repository's Root role, etc.  Unfortunately, at other places the document talks about "The Root role" and "The Targets role", etc, implying that there is just one Root role, one Targets role, etc.  (And therefore that the Director and Image repository have copies of the same roles: ie, the Director's Root is the same as the Image Repository Root).  Could this be made clearer by replacing "The Root role" with "A Root role" and similar changes?  Also, in the #targets_role subsection of #roles, it is stated that there are other custom-defined roles.  Do these custom-defined roles act like Target roles, and could there existence be listed in places like the "Uptane Role Terminology" where the various roles are enumerated?  In particular, in the "Common Metadata Structures" it is not clear if custom roles should be of type "Targets" or if this section is incomplete. Does a Root role sign the public keys for these custom roles as well?

6. In the "Out of Scope" section, it says that "Problems associated with OBD or UDS programming of ECUs, such as authentication of communications between ECUs" are out of scope.  Authentication of communications between ECUs is a problem that isn't restricted to OBD/UDS programming.  This statement could be misread to imply that either
    - Uptane will only work on vehicles in which communication between ECUs is authenticated, or
    - Update assumes that an adversary that controls one of the ECUs in a car will be polite and never force it lie to the other ECUs about who it is.

    I presume that neither of these are meant.  Perhaps a better example could be chosen, and the threat model explicitly state that compromised ECUs can take advantage of unauthenticated communication channels between ECUs?

7. The spec assumes that the primary is able to communicate directly with all of the secondaries.  Is this realistic?  Even if one assumes that gateways will forward communications to/from the primary and secondaries on another network, Uptane will have to be aware of this because the gateways themselves might be updated.

8. In the "Targets Metadata" subsection, it is explicitly stated that a Targets metadata file MUST provide information about EVERY image in the repository.  I would think that it is not feasible to send to every vehicle the complete list of all images for all parts that have ever existed!  Presumably this should be re-worded.

9. In the Time Server section, it says that "it SHALL sign each token together with the current time," which seems to say that if n tokens are sent to it, the server will send back n signed objects: token 1 together with the time, token 2 with the time, etc.  I presume that the server will actually combine the time with the list of tokens and do one signature operation on the combination.

10. In the "Repository mapping metadata" section it states that the repository mapping metadata MUST contain a list of repositories that MUST sign the targets metadata for the image paths.  However, I cannot find where this is used.  Should this be in the full verification process?  And does the partial verification process use this as well?

11. Technically, this algorithm has another obvious vulnerability: if the attacker takes over the primary (which it is allowed to in the threat model), then it can deny installation of updates by simply refusing to run the update process.  Of course, it isn't reasonable to expect otherwise: if an attacker is preventing the use of the wireless communication mechanism, you aren't going to be doing any wireless updates.  We also don't want to change the threat model to say that the primary ECU is trusted because there would be no reason to have such a complicated mechanism as Uptane if we trusted primaries.  Instead, I think we need a more nuanced description of what security Uptane promises, stating what security is achieved under the various conditions: what are your guarantees even if the primary is compromised, a secondary is compromised, etc.

12. Quite a few of these issues revolve around clarity.  I like the description of the time server (despite point 9 above) because it states exactly what messages it expects to receive and what it will return.  Can we do the same for the rest of the system?  To be precise, I would recommend having two tables:
    1. Data Table:
        This table would have for each kind of entity in the system (Director, Image Repository, Time Server, primary ECU, secondary ECU, and other repositories):
        - which private crypto keys it has,
        - which public crypto keys it has,
        - what other data it has
    2. Function Table:
        This table would have for each kind of entity in the system a list of which messages it will respond to, including
        - what entity it expects to receive this message from,
        - what data will be included in the message (including if it is signed and, if so, by what),
        - what the response to this message should be
     
     I think having these tables would make the implementation specification much clearer, and much easier to verify.

13. As a process concern, at a number of places the specification says things like "A primary ECU SHALL download metadata and images following the rules specified in {{TAP-5}}".  Would this cause problems with the IEEE, since it would allow changes to be made to the specification by the maintainers of TAP, outside of the IEEE process?

Thanks!

**Comment by JustinCappos** [comment]
Thanks for the feedback!

Can you break these out into separate issues?  It is hard to track as a big
list.

**Comment by JustinCappos** [comment]
I will say that #13 isn't an issue w/ IEEE/ISTO unless we collectively
decide it shouldn't work this way.

The TAPs are effectively standards docs and won't change in a relevant way
for Uptane w/o feedback from this community.

I'm happy to discuss more if there are thoughts / concerns from others.

**Comment by iramcdonald** [comment]
Hi,

I disagree with Justin about #13 (normative out-references to TAP-5).

I strongly feel that all out-references to TAP-n should be changed in the
IEEE-ISTO Uptane Alliance standard to SHOULD (Recommendation).

I think that automotive OEMs would dislike the current normative out-refs
and I'm sure that SAE vehicle security committees would dislike them.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by JustinCappos** [comment]
Okay, let's discuss this in the workshop.

I'm not opposed to changing this.  I don't feel that strongly.

Justin
