### ISSUE TITLE
Writing flash

### ISSUE THREAD

**Issue by sam-m-weber** [uptane/uptane-standard#46]
In previous discussions, it was stated that because flash memory fails if it is written too many times, the number of writes should be minimized.  My recollection is that writing every time an update is checked for was considered too frequent.  Is this still a consideration and, if so, what is the acceptable frequency of updates?

(I had previously put this in with other minor issues, but Justin requested that I make it a separate issue.)

**Comment by JustinCappos** [comment]
Since this will be handled by folks during deployment, do you want to propose PR for the deployment considerations that indicates that people deploying Uptane need to take flash write wear into account?

If so we will review it.  My view is that it seems perhaps a bit too obvious to state, but I don't feel strongly.

**Comment by iramcdonald** [comment]
Hi,

In Deployment Considerations, I think flash wear is important to address.
It's actually a hard problem throughout the computer industry.

The TCG TPM 2.0 has mechanisms for what I'll call "lazy" writes to NVRAM
to mitigate flash wear, based on the wildly wrong assumption that almost
all system shutdowns are orderly and the TPM firmware will have enough
warning to do a commit on all the pending NVRAM writes - doesn't work
out well in the real world, of course (imagine a monotonic counter that
never got incremented a number of times and was protecting secure
boot integrity).

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by sam-m-weber** [comment]
I think that the issue is whether the current Uptane specification
- requires that flash be updated too often, or
- if implemented in the obvious fashion would result in too frequent flash updates, but there are mitigation strategies available that could be used.

If neither of these cases is true, then there is no problem.  If the first holds, then Uptane needs to be changed to address this.  If the second holds, then I think we have to decide whether Uptane should be changed or whether guidance should be given on how to avoid this problem.  (As Ira says, there are mechanisms that purport to avoid flash wear which work really badly in the real world.)

**Comment by JustinCappos** [comment]
Since we don't specify when an update must occur (could be every day,
month, year, etc.), we don't *require* it to be updated too often.

I don't know what the obvious fashion is in this case.  Perhaps check on
ignition would be something commonly thought of?  I suppose it would be
fine to add a short statement mentioning that the deployment should
consider flash wear when considering how often to perform updates.

**Comment by jhdalek55** [comment]
Any idea where such a statement would go? And is this in the standards or are we still talking about deployment?

**Comment by JustinCappos** [comment]
Definitely in the deployment guidelines.

**Comment by jhdalek55** [comment]
Ok. Then do we want to make a note of it for the Deployment document and
remove it as an issue here?

Lois

**Comment by sam-m-weber** [comment]
Maybe.  I think Justin's statement "Since we don't specify when an update must occur...we don't *require* it to be updated too often" might be misread, since it seems to imply that a flash-write only occurs when an update is applied to an ECU.  Currently, however, as I read it, Uptane has every ECU do a flash-write every time updates are checked for. 

Is this unreasonable, even if this is documented in the deployment document?  And, of course, is a flash-write every check what is intended?

**Comment by iramcdonald** [comment]
Hi,

For a 15-to-30 year life ECU, *no*, a flash write every check for
updates isn't reasonable (unless ECUs and vehicles are lazy
and never check for updates in a timely manner).

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by JustinCappos** [comment]
If an ECU performs a check every day and always writes to the same block, a
10K write cycle flash memory would wear out after 27.4 years.  Do ECUs, as
they are programmed today, do any write leveling?

Even if not, just writing the thing you're downloading to a different
location (which is required by the spec) would mean you write to each block
1/2 as often.

This all being said, the meat of this discussion absolutely does need to be
captured in the deployment guidelines.

**Comment by iramcdonald** [comment]
Hi Justin,

I agree the whole topic needs to be discussed in Deployment
Considerations.

No, ECUs often don't do any wear-leveling at all.  Also for cost
reasons, they sometimes use el cheapo flash that doesn't have
a reliable 10K cycle lifetimes.  Also, for security, the ECUs may
well be keeping all these counters in *dirt* cheap hardware
security elements (w/ very minimal onboard flash).

We should at least caution against foolish designs, but that's
only one finger in the dike...

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by JustinCappos** [comment]
I added text to the deployment considerations (E.7) to address this.
