### ISSUE TITLE
Uptane security guarantees

### ISSUE THREAD

**Issue by sam-m-weber** [uptane/uptane-standard#54]
Technically, this algorithm has another obvious vulnerability: if the attacker takes over the primary (which it is allowed to in the threat model), then it can deny installation of updates by simply refusing to run the update process.  

Of course, it isn't reasonable to expect otherwise: if an attacker is preventing the use of the wireless communication mechanism, you aren't going to be doing any wireless updates. 

We also don't want to change the threat model to say that the primary ECU is trusted because there would be no reason to have such a complicated mechanism as Uptane if we trusted primaries.  Instead, I think we need a more nuanced description of what security Uptane promises, stating what security is achieved under the various conditions: what are your guarantees even if the primary is compromised, a secondary is compromised, etc.

**Comment by JustinCappos** [comment]
This is described already in the threat model and analysis as a "drop-request attack" (if the traffic is outright dropped) or a "freeze attack" (if old metadata is replayed).  This is covered repeatedly in the standards document and is also discussed in the papers about Uptane.  

My belief is that the standards docs really aren't meant to argue about the security of the system, but instead are supposed to say how to implement Uptane.  We've already published a variety of documents that describe the security properties and limitations.  I don't think this content belongs in the standard.

**Comment by iramcdonald** [comment]
Hi,

I know this was closed, but I think it's an important point to make in
the main Uptane standard that a Primary might be compromised
and a Full or Partial Verification Secondary should be able to
determine that the Primary is misbehaving and gracefully resist
accepting bad update instructions from that upstream Primary.

Am I missing something in your Uptane philosophy Justin?

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by JustinCappos** [comment]
Yes, you are correct that dealing with a malicious or buggy primary is
central to what Uptane provides.

I'm not sure where this fits in the standard.  We do say this repeatedly in
other documents that are more focused on the security guarantees Uptane
provides, etc.

Where should tis be added?

**Comment by sam-m-weber** [comment]
(Can this be re-opened?)

Either the "Threat Model" or "Design Requirements" sections would be reasonable, I think.  

(And if a secondary is taken over, is it acceptable for it to prevent all vehicle updates?  Or to prevent updates to another ECU?)

**Comment by JustinCappos** [comment]
I guess I'd rather raise this discussion to the philosophical level of how much of the security analysis, etc. should be repeated in the specification.  I think once we agree on this, then what to do about this ticket is clearer

**Comment by sam-m-weber** [comment]
I think it is extremely important to state in the specification what security incidents Uptane will prevent.

Part of any specification that I am aware of is a statement of what the entity being described is supposed to do.  In Uptane's case, this is a level of security.  Uptane requires a large investment by its users: they have to develop new code and require it be deployed by all of their suppliers.  It is important, then, that they be clear what benefits they should expect.  In particular, they shouldn't expect more of Uptane than it will provide!

**Comment by JustinCappos** [comment]
We resolved in the Uptane workshop today to have a link to the technical materials that contain this information rather than duplicating it in the spec.
