### ISSUE TITLE
Request for data and message tables

### ISSUE THREAD

**Issue by sam-m-weber** [uptane/uptane-standard#55]
Quite a few of the issues that I previously raised revolve around clarity.  I like the description of the time server (despite issue 52) because it states exactly what messages it expects to receive and what it will return.  Can we do the same for the rest of the system?  To be precise, I would recommend having two tables:
1. Data Table:
    This table would have for each kind of entity in the system (Director, Image Repository, Time Server, primary ECU, secondary ECU, and other repositories):
    - which private crypto keys it has,
    - which public crypto keys it has,
    - what other data it has

2. Message Handler Table:
    This table would have for each kind of entity in the system a list of which messages it will respond to, including
    - what entity it expects to receive this message from,
    - what data will be included in the message (including if it is signed and, if so, by what),
    - what the response to this message should be
     
I think having these tables would make the implementation specification much clearer, and much easier to verify.  For instance, when reading an algorithm you'd be able to check that an ECU actually has the data that the algorithm uses, be able to check that each piece of data is updated and maintained appropriately, and ensure that you've implemented all the message handlers that you need.

**Comment by JustinCappos** [comment]
If you'd like to send a PR for this, feel free.

**Comment by sam-m-weber** [comment]
Every organization that attempts to implement Uptane will have to determine all the messages that an ECU has to handle and make sure that all of them are handled correctly.  Therefore, it seems to be rather unpleasant that this information isn't made clear in the specification and a likely source of errors.

I'd be happy to write a PR for this (although a subcontract would have to be issued to CMU Cylab to cover this).  However, one of the reasons that I raised this issue is that I'm not certain that all of this information is actually in the current specification.

**Comment by iramcdonald** [comment]
Hi,

I agree with Sam about the importance of these tables.

Also, any conceivable Uptane Certification procedure would certainly
need those tables for conformance checking.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by JustinCappos** [comment]
Some of this is uniform across the standard, but much of it is specific to
the profile (i.e. the wireline format).  How should we handle this?

**Comment by iramcdonald** [comment]
Hi Justin,

I'm confused.

I would have thought that the required Uptane application layer
metadata elements would have been invariant, irrespective of
the protocol binding (the correct standards term, i.e., what you
called the "wireline format")?

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by JustinCappos** [comment]
So, quite a bit of what goes into what Sam called the "Message Handler
Table" will differ by wireline format.  Or at least the set of things we
would list would be a minimum and quite under-specified.  So, for example,
if we are talking about hardware IDs and some profiles specify using a key
value store and others use strings, we would just want to say "hardware ID"
in the spec.

Also, some implementers may want to pass additional information along that
is not required by the spec.  I don't think this is actually an obstacle,
but just wanted to mention that the table would not be definitive or
specific...

After thinking as I was writing this message up, I don't see either of
these issues as actually problematic.

**Comment by iramcdonald** [comment]
Hi Justin,

This thread goes to the heart of my concern about whether it could
ever be practical to have a formal certification process for Uptane
implementations.

There are no rigorous definitions (or alternative definitions) for
specific normalization and encoding of metadata elements.

I cannot imagine how "interoperability" can be reasonably applied
to multiple Uptane implementations.  At least not what IETF or
IEEE normally mean by "interoperability" (which always includes
protocol element formats on the wire).

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by JustinCappos** [comment]
In the workshop today, we talked around this issue a bit.  I think the resolution that makes the most sense is to have the profiles and the spec list this at the appropriate level of specificity.  

If anyone disagrees, please raise it here.  Otherwise, we will add this moving forward.

**Comment by tkfu** [comment]
Action plan from 03/13 standards call: @OTAINFO will work on this and submit a PR.

**Comment by jhdalek55** [comment]
Update from 3/27 standards call @OTAINFO is working on this issue and will submit a PR.

**Comment by tkfu** [comment]
@OTAINFO: Regarding your trouble with submitting a PR, there's documentation on how to use GitHub Flow to contribute content in the readme of this repository: https://github.com/uptane/uptane-standard#contributing

**Comment by OTAINFO** [comment]
The data and messages are added. I will review it one more time and open a pull request.

**Comment by jhdalek55** [comment]
Thanks for completing this


Lois

On Mon, Apr 08, 2019 at 02:07 AM, OTAINFO wrote:

The data and messages are added. I will review it one more time and open 
a pull request.


—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uptane_uptane-2Dstandard_issues_55-23issuecomment-2D480696018&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=Tme7oPxP3RLkdGuX9442ItqOM0obHJT0_eGY9BU5rVM&s=7_1u2xrOvJUHRioeQmBTH8XiWhMcZgTZ3eOq5iNnyhY&e=> 
, or mute the thread 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AN5qX3E61EUvW0e9QFexDwNZtOZPhjQGks5vetyagaJpZM4bFTGo&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=Tme7oPxP3RLkdGuX9442ItqOM0obHJT0_eGY9BU5rVM&s=jO8v5PW4iZtTKrvjQS-4tTBI6OXjhANnjCpDqEtlIQk&e=> 
.

**Comment by jhdalek55** [comment]
In the 4/10 Standards call @OTAINFO reported that he has prepared a draft will be submitting a PR for this shortly.

**Comment by jhdalek55** [comment]
On the 4/24 Standards Call, it was noted that a PR had been submitted, but the issue required a different approach. The Standards group is seeking a volunteer to submit a new PR to present this information.

**Comment by jhdalek55** [comment]
I posted a notice on the Uptane Forum asking for a volunteer to prepare these tables.

**Comment by jhdalek55** [comment]
The posting on the forum has so far attracted no volunteers. Can I ask the Standards members if one of you can take this on?

**Comment by JustinCappos** [comment]
We could also just wontfix this.  I think this is of dubious value,
especially as the profile will contain the actual relevant information of
this type.

Justin

**Comment by OTAINFO** [comment]
Hi Justin,

I think this ticket is important and would be willing to work with someone
to crack it out.  To get a clear path on this ticket, it will be good if we
can talk with OEMs or Update providers to OEMs and find out the current
update communication sequence and message contents. Using this information,
create a proposal for Uptane messaging requirements.

In my opinion, these tables will be helpful for new adopters of Uptane.

Best,
Akshay

**Comment by OTAINFO** [comment]
FYI: In my previous message "ticket" means "issue".

**Comment by mnm678** [comment]
I agree that the data and message tables would fit better for profiles than
the standard. Profiles are already required to have most of the information
that would be in these tables, and the table format might make it easier to
read and implement the profile. I can adjust the profile requirements to
include this.

-Marina

**Comment by jhdalek55** [comment]
@sam-m-weber As you can probably tell from the lengthy discussion here, we have decided not to include the data and message tables proposed in the standard. Since you introduced this issue thread, the committee has developed the idea of using profiles, or a separate layer of customizable code, to specify protocol, usage, and formats. As such, each profile will require its own set of data and message tables, so creating master tables for the Standard was not needed. Thank you for calling this issue to our attention. It will be addressed, but in a different manner. So we are closing this issue.

**Comment by sam-m-weber** [comment]
I'm afraid I don't understand the rationale behind this decision, especially the statement "Specific message flows and required metadata/data elements are very specific to implementations."

For example, when the specification states that the primary must "Send metadata to secondaries", clearly the message format and probably the addressing of the message(s) that are sent will be implementation-specific.  However, shouldn't the contents of the message(s) itself be determined and implementation-independent?

As a second example, say one has a secondary ECU which does partial verification.  Shouldn't which cryptographic keys this ECU has be determined by Uptane, and not depend upon the implementation?

**Comment by JustinCappos** [comment]
Some parts are standard (and required).  Others are not.

The profiles are the place where details exist at a finer grained level
(which is more appropriate for this representation).  So, we've decided to
move it there.

**Comment by iramcdonald** [comment]
Hi Sam,

In addition the profiles will list the actual set of implementation messages
(operations).

That is, the Uptane Standard will NOT specify the exact set of messages
or the complete ordering of message exchanges to accomplish the specific
functions.  Partly, this recognizes and embraces the existing divergence
of implementor choices in message sets.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by sam-m-weber** [comment]
Although I don't want to continue beating a dead horse, I'm still puzzled about how the security audits were performed without this information.  Perhaps I could get a copy of said audits, and this will clarify things?

The NCC's audit is on the website, and SWRI's audit was sent on the mailing list, so I have those.  It doesn't look like Cure53's audit is on the website however, so could I get a copy of it?  And, didn't the Software Engineering Institute do another audit?

Thanks,

  -- Sam Weber
      CMU CyLab

**Comment by JustinCappos** [comment]
You can find the Cure53 audit here:  https://theupdateframework.github.io/audits.html  I don't recall any SEI audit, but may have forgotten.

It isn't that the auditors didn't have this information.  They read the code and/or spec to get this information. 

Also, in the future it is probably best to send a message to the list to ask basic questions.  We have a general rule not to add to obsolete issues or include items that are off topic in an issue.
