### ISSUE TITLE
Full verification secondaries requiring all delegated metadata roles?

### ISSUE THREAD

**Issue by awwad** [uptane/uptane-standard#59]
Section {#send_metadata_primary} says [here`*`](https://github.com/uptane/uptane-standard/blame/master/uptane-standard.md#L736) that full verification secondaries must have "a complete copy of all repository metadata".  Is this meant to include all delegated targets roles on an image repository?  That could be a lot.  Is it meant instead to mean all top-level metadata?  All top-level metadata and any delegated targets roles necessary for the verification of relevant images?

`*` (Sorry for the clumsy `git blame` link; it's the only line-specific link I seem to be able to do for an `.md` file.)

**Comment by tkfu** [comment]
That's a good point. As far as I can see, the security properties are the same for either option, so I think it's okay to make it a SHOULD. I'm preparing a quick PR to address this now.

**Comment by tkfu** [comment]
#62 addresses this. Reviews/comments welcome.

**Comment by jhdalek55** [comment]
Can this issue be closed now? The PR addressing it has been marged.

**Comment by awwad** [comment]
Resolved, yes, thanks. :)
