### ISSUE TITLE
Rendering of full verification steps doesn't work well

### ISSUE THREAD

**Issue by tkfu** [uptane/uptane-standard#63]
The full verification procedure goes 6 levels deep in the section that describes how to resolve delegations, and this makes the HTML rendering really ugly, wrapping the text of the deeply-nested instructions at one word per line:
<img width="633" alt="screen shot 2019-02-23 at 18 26 50" src="https://user-images.githubusercontent.com/4501758/53285175-b1db3280-3798-11e9-8081-fd8e9b7f3b35.png">

This, obviously, isn't ideal.

**Comment by iramcdonald** [comment]
Hi,

I suggest unwinding the deeply nested levels into separate named/numbered
sections and
using forward references from the top-level algorithm.

Also, deeply nested verification algorithms are inherently suspect.  Errors
and side-effects
from ordering become very hard to spot (until they hit you in the field).

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by trishankatdatadog** [comment]
I agree --- the nesting has gotten especially ridiculous with the recent
TAP 3 clarifications.

**Comment by tkfu** [comment]
I’m working on a PR for this now.

On Feb 23, 2019, at 22:09, Trishank K Kuppusamy <notifications@github.com<mailto:notifications@github.com>> wrote:

I agree --- the nesting has gotten especially ridiculous with the recent
TAP 3 clarifications.

**Comment by tkfu** [comment]
Closed by #75.
