### ISSUE TITLE
Please check new Uptane costs section...

### ISSUE THREAD

**Issue by JustinCappos** [uptane/uptane-standard#69]
I took a rough cut at a section that talks about the computational costs of Uptane in E.8 of the deployment considerations.  This is all 'off-the-cuff' and is just meant as an outline of how this would go.  Fixes welcome (and likely needed)!

**Comment by tkfu** [comment]
On the 03/13 standards call, we discussed closing this and moving it to https://github.com/uptane/uptane.github.io/, but didn't reach a conclusion. Discussion about the most appropriate place/format for deployment considerations will continue on the mailing list.

**Comment by jhdalek55** [comment]
This was closed as per the discussion on the 3/27 Standards conference call. The new copy will be reviewed as part of the roll-over of materials to Markdown files.
