### ISSUE TITLE
Clarify ability to add custom install instructions

### ISSUE THREAD

**Issue by mnm678** [uptane/uptane-standard#7]
Some ECUs require custom installation instructions. See the discussion in [#5](https://github.com/uptane/uptane-standard/issues/5) for background.

A description of how uptane can be used to include these custom instructions should be included in the Deployment Considerations document.

**Comment by mnm678** [comment]
@OYTIS
I added section D.9 to [Deployment Considerations](https://docs.google.com/document/d/17wOs-T7mugwte5_Dt-KLGMsp-3_yAARejpFmrAMefSE/edit?usp=sharing) to address this issue. Any feedback would be appreciated.

**Comment by mnm678** [comment]
@OYTIS
I added section D.9 to [Deployment Considerations](https://docs.google.com/document/d/17wOs-T7mugwte5_Dt-KLGMsp-3_yAARejpFmrAMefSE/edit?usp=sharing) to address this issue. Any feedback would be appreciated.

**Comment by JustinCappos** [comment]
I believe @mnm678 has addressed this.  If there are concerns, please reopen.
