### ISSUE TITLE
Refer to other specifications

### ISSUE THREAD

**Issue by JustinCappos** [uptane/uptane-standard#72]
The Uptane specification should appropriately refer to other specification documents.  The requirements we have are higher (and often a proper super-set) of many related standardization efforts.  We should somewhere make it clear our relation to these specs.

@iramcdonald, we'd appreciate some guidance here.  We can do most of the work, but need to know what things we might be missing and/or how to find them.

**Comment by tkfu** [comment]
Just for the mechanics of this: there's an existing structure in the IETF RFC format that we use; links (or citations, in the case of published standards that aren't online) can be added as either normative or informative in the header of the document, and then referenced later on. We already do this for a number of RFCs, as well as for TAPs from TUF.

**Comment by tkfu** [comment]
On the 03/13 standards call, we agreed that we don't want to overspecify and force people into using particular formats, encodings, etc., but also that we can use some reasonable judgement: for example, we are comfortable in requiring RFC5198 encoding of strings in metadata to facilitate comparison.
