### ISSUE TITLE
How many places should we list HW IDs?

### ISSUE THREAD

**Issue by trishankatdatadog** [uptane/uptane-standard#74]
Right now, HW IDs are listed in both: (1) the custom targets metadata on both the director and image repositories, and (2) delegations on the targets metadata of the image repository.

This seems redundant and error-prone (could lead to accidental self-denial-of-service "attacks"). However, it's not trivial to remove one or the other, especially because the first method is already in use. We need to discuss how to best resolve this.

For more details, see PR #71

**Comment by tkfu** [comment]
On the 03/13 standards call, we agreed to discuss this further on the 03/27 standards call, since neither @awwad nor @trishankatdatadog were able to be present today. Comments and suggestions in the thread here are, of course, still welcomed.

**Comment by jhdalek55** [comment]
On the 3/27 Standards call, @trishankatdatadog agreed to make a few edits and then close this issue.
