### ISSUE TITLE
What SHOULD be included in the ECU Manifest?

### ISSUE THREAD

**Issue by jhdalek55** [uptane/uptane-standard#76]
What are the key data that must be completed here. I believe @iramcdonald and @cajun-rat  offered to provide some language for this.

**Comment by tkfu** [comment]
On the 03/13 standards call, we agreed to leave this issue open for the next two weeks so that people can comment here informally about what kinds of things to include. We will ask for a volunteer to aggregate the suggestions and write the text on the 03/27 standards call.

**Comment by patrickvacek** [comment]
Are Sections [5.4.2.1.1](https://uptane.github.io/uptane-standard/uptane-standard.html#vehicle_version_manifest) and 5.4.2.1.2 not enough to describe this already? I checked our implementation of what we send and the default information is exactly what is described there.

**Comment by tkfu** [comment]
@patrickvacek: The idea here is to gather ideas about what would be _useful_ to include in the custom metadata. For example, perhaps a useful custom field would be a list of libraries and versions used in building the image, or some sort of diagnostic data. We're leaving it open especially to folks from OEMs to give their input on the kinds of things that would be helpful here.

We're not talking about changing the required parts--no new or modified SHALLs/MUSTs. Just suggestions for adding some SHOULDs.

**Comment by jhdalek55** [comment]
This was closed on 3/27 after discussion on the Standards calls noted there had been no suggestions generated on the topic.
