### ISSUE TITLE
Adding cautionary note in the Standard with respect to Bugs

### ISSUE THREAD

**Issue by jhdalek55** [uptane/uptane-standard#77]
We need to add a statement in the Standards document along the lines that bugs must be fixed in the most prompt and and efficient manner possible

**Comment by JustinCappos** [comment]
I think this got a bit garbled in the meeting notes.  The point here was to make it so that any Uptane implementation must patch bugs promptly.  This isn't about external references to other documents (unless I was misunderstanding the conversation at that point).

**Comment by jhdalek55** [comment]
Ok. I hadn't shared the link yet, so I fixed it in the repo and the 
document.


Lois

On Thu, Mar 07, 2019 at 06:24 PM, Justin Cappos wrote:

I think this got a bit garbled in the meeting notes.  The point here was 
to make it so that any Uptane implementation must patch bugs promptly. 
This isn't about external references to other documents (unless I was 
misunderstanding the conversation at that point).


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uptane_uptane-2Dstandard_issues_77-23issuecomment-2D470742234&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=Vt4Rz8c6YjYLQNTNOEw2wyEThClLXaevxpGqFHkbR5Q&s=wxXnb98vuwDnuDNtehCLkDTHHPvKHCU6cmX6tZZgnQ0&e=> 
, or mute the thread 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AN5qXwFIblQQd9w7jhzKgyYV0KognIjeks5vUZ-2D8gaJpZM4bkC44&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=Vt4Rz8c6YjYLQNTNOEw2wyEThClLXaevxpGqFHkbR5Q&s=ANV3r559mH8VXQoGddlo6RsjdCmvI77I0fuItgD3-Cc&e=> 
.

**Comment by tkfu** [comment]
On the 03/13 standards call, @jhdalek55 volunteered to make a PR for this addition.

**Comment by jhdalek55** [comment]
Closing via corrections in PR #87
