### ISSUE TITLE
ECU identifiers are a SHOULD, not a MUST

### ISSUE THREAD

**Issue by tkfu** [uptane/uptane-standard#82]
ECU identifiers (e.g. serial numbers for ECUs that should install a particular target) are currently specified as a SHOULD in Director targets metadata. Shouldn't this be a MUST?

**Comment by iramcdonald** [comment]
Hi,

My two cents - YES.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434
