### ISSUE TITLE
Confused description about ECU keys

### ISSUE THREAD

**Issue by willllllllllllll** [uptane/uptane-standard#89]
{#director_repository}: 
 > The Director MAY encrypt images for ECUs that require them, either by encrypting on-the-fly or by storing encrypted images in the repository.

does the **storing encrypted images...** mean use offline ECU key? I don't think it is applicable since ECU key is unique.

{#inventory_db}:
> Per ECU:
>
>- A unique identifier (such as a serial number)
>- The vehicle identifier the ECU is associated with
>- **A public key**

Here, **a public key** means ECU key? if yes, this is not precise enough, since ECU key has option to use symmetric key.

And, ECU key are also used by ECU to sign version manifest and image decryption. so it should be installed during ECU production. It indicates there should be key shipment or registration (to OEM), right?

**Comment by jhdalek55** [comment]
On  the 3/27 conference call @patrickvacek agreed to review this issue this issue and open a PR.

**Comment by tkfu** [comment]
That was actually me--we were just using the same microphone.

**Comment by jhdalek55** [comment]
Ok. Sorry about the confusion.

Lois

**Comment by tkfu** [comment]
Regarding the first question, Uptane is pretty flexible about options for encrypted images. You might find, for example, that encrypting every image uniquely per ECU is overkill, but you still want some level of encryption. So, you decide to store an encrypted image on the director repo with some master key, send that decryption key to each individual ECU (encrypted with the ECU's key), and periodically rotate the master key. We will try to make sure a discussion of this ends up in the deployment considerations.

I've opened up #96 to fix the second issue.
