### ISSUE TITLE
Targets Metadata metadata about images

### ISSUE THREAD

**Issue by mnm678** [uptane/uptane-standard#91]
At the top of Targets Metadata is its stated that targets metadata "MAY contain metadata about images on a repository". Later in the Targets Metadata section (under Custom Metadata) it says that "the Targets metadata file SHOULD contain extra metadata for each image on the repository". Is this a SHOULD or a MAY? Or are these statements referring to different metadata?

**Comment by trishankatdatadog** [comment]
Yeah, this is partly what I meant in #71

**Comment by jhdalek55** [comment]
on the 3/27 Standards call, @trishankatdatadog  agreed to address this issue.

**Comment by jhdalek55** [comment]
On the 4/10 Standards call, @trishankatdatadog noted he was still working on this but will complete it shortly.

Lois

**Comment by tkfu** [comment]
I'm reopening this because of my comment in #100.

**Comment by jhdalek55** [comment]
@trishankatdatadog @tkfu  can one of you let me know the status of this issue. Has the PR #102 mentioned above resolved the problem?

**Comment by jhdalek55** [comment]
On the 4/24 Standards Call, the confusion over PR#102 opening and closing was addressed. @tkfu will issue a new PR to close this out.

**Comment by jhdalek55** [comment]
On the 5/8 Standards call, @patrickvacek noted that he believed this was still on @tkfu TODO list and that he will follow up with @tkfu .
